# Generated by Django 6.0.1 on 2026-01-23 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dòng họ')),
                ('village', models.CharField(max_length=200, verbose_name='Làng')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('chi_count', models.PositiveIntegerField(default=8, verbose_name='Số Chi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dòng họ',
                'verbose_name_plural': 'Các dòng họ',
            },
        ),
        migrations.CreateModel(
            name='Chi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Số Chi')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tên Chi')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_set', to='core.family')),
            ],
            options={
                'verbose_name': 'Chi',
                'verbose_name_plural': 'Các Chi',
                'ordering': ['number'],
                'unique_together': {('family', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(max_length=50, unique=True, verbose_name='ID cũ')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('generation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Đời thứ')),
                ('is_dinh', models.BooleanField(default=False, verbose_name='Tính Đinh')),
                ('member_type', models.CharField(choices=[('blood', 'Dòng trực hệ'), ('spouse_in', 'Dâu/Rể'), ('child_out', 'Cháu ngoại')], default='blood', max_length=20, verbose_name='Loại thành viên')),
                ('birth_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Con thứ')),
                ('birth_date', models.CharField(blank=True, max_length=50, verbose_name='Ngày sinh')),
                ('death_date', models.CharField(blank=True, max_length=50, verbose_name='Ngày mất')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.chi', verbose_name='Chi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='core.familymember', verbose_name='Cha')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='core.familymember', verbose_name='Mẹ')),
                ('spouses', models.ManyToManyField(blank=True, to='core.familymember', verbose_name='Vợ/Chồng')),
            ],
            options={
                'verbose_name': 'Thành viên',
                'verbose_name_plural': 'Thành viên',
                'ordering': ['chi', 'generation', 'birth_order', 'name'],
            },
        ),
    ]
