# Generated by Django 6.0.1 on 2026-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID cũ'),
        ),
    ]
