# Generated by Django 6.0.1 on 2026-01-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_familymember_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Thuộc tính mở rộng'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Công khai'),
        ),
    ]
