# Generated by Django 6.0.1 on 2026-01-23 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_familymember_attributes_familymember_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='member_type',
            field=models.CharField(choices=[('blood', 'Dòng trực hệ'), ('spouse_in', 'Dâu/Rể'), ('child_out', 'Cháu ngoại'), ('adopted_in', 'Nhập tịch'), ('adopted_child', 'Con nuôi')], default='blood', max_length=20, verbose_name='Loại thành viên'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_person_name', models.CharField(max_length=100, verbose_name='Tên người liên kết')),
                ('to_person_gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], default='male', max_length=10, verbose_name='Giới tính')),
                ('link_type', models.CharField(choices=[('blood_out', 'Cháu ngoại/Con gái ra'), ('adopted', 'Con nuôi'), ('step', 'Con riêng'), ('friend', 'Bạn bè/Bạn thân'), ('partner', 'Đối tác kinh doanh'), ('neighbor', 'Hàng xóm/Láng giềng'), ('other', 'Quan hệ khác')], max_length=20, verbose_name='Loại quan hệ')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Nhãn tùy chỉnh')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_public', models.BooleanField(default=False, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links_from', to='core.familymember', verbose_name='Từ thành viên')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
                ('to_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links_to', to='core.familymember', verbose_name='Thành viên liên kết (nếu có trong cây)')),
            ],
            options={
                'verbose_name': 'Quan hệ xã hội',
                'verbose_name_plural': 'Các quan hệ xã hội',
                'ordering': ['-created_at'],
            },
        ),
    ]
