# Generated by Django 6.0.1 on 2026-01-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_familymember_member_type_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='seniority_note',
            field=models.CharField(blank=True, help_text='Ghi chú thứ bậc so với ego (anh/em/cô/chú...)', max_length=50, verbose_name='Thứ bậc'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link_type',
            field=models.CharField(choices=[('grandchild_external', 'Cháu ngoại'), ('daughter_married', 'Con gái đã lấy chồng'), ('adopted_child', 'Con nuôi'), ('foster_parent', 'Bố/Mẹ nuôi'), ('step_child', 'Con riêng'), ('in_law', 'Thông gia'), ('naturalized', 'Nhập tịch'), ('friend', 'Bạn bè/Bạn thân'), ('partner', 'Đối tác kinh doanh'), ('neighbor', 'Hàng xóm/Láng giềng'), ('other', 'Quan hệ khác')], max_length=20, verbose_name='Loại quan hệ'),
        ),
        migrations.CreateModel(
            name='SpouseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wife_order', models.PositiveIntegerField(default=1, help_text='1=Bà Cả, 2=Bà Hai, 3=Bà Ba...', verbose_name='Thứ tự')),
                ('marriage_date', models.CharField(blank=True, max_length=50, verbose_name='Ngày cưới')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('husband', models.ForeignKey(limit_choices_to={'gender': 'male', 'is_dinh': True}, on_delete=django.db.models.deletion.CASCADE, related_name='wife_relations', to='core.familymember', verbose_name='Chồng (Đinh)')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband_relations', to='core.familymember', verbose_name='Vợ')),
            ],
            options={
                'verbose_name': 'Quan hệ vợ chồng',
                'verbose_name_plural': 'Các quan hệ vợ chồng',
                'ordering': ['husband', 'wife_order'],
                'unique_together': {('husband', 'wife')},
            },
        ),
    ]
