# Generated by Django 6.0.3 on 2026-04-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_spouse_relation_and_expand_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genealogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên gia phả')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('total_people', models.PositiveIntegerField(default=0, verbose_name='Tổng số người')),
                ('total_generations', models.PositiveIntegerField(default=0, verbose_name='Tổng số thế hệ')),
                ('json_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gia phả',
                'verbose_name_plural': 'Gia phả',
            },
        ),
        migrations.CreateModel(
            name='GenealogyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=50, verbose_name='Mã người (ID)')),
                ('name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('generation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thế hệ')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Nơi ở')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('father_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã cha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genealogy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.genealogy', verbose_name='Gia phả')),
            ],
            options={
                'verbose_name': 'Thành viên gia phả',
                'verbose_name_plural': 'Thành viên gia phả',
                'unique_together': {('genealogy', 'person_id')},
            },
        ),
        migrations.CreateModel(
            name='GenealogySpouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên vợ')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouses', to='core.genealogyperson', verbose_name='Người chồng')),
            ],
            options={
                'verbose_name': 'Vợ',
                'verbose_name_plural': 'Vợ',
                'ordering': ['person', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GenealogyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Cha/Con'), ('spouse', 'Vợ/Chồng'), ('sibling', 'Anh/Em')], max_length=20, verbose_name='Loại quan hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.genealogyperson', verbose_name='Từ người')),
                ('genealogy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.genealogy', verbose_name='Gia phả')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.genealogyperson', verbose_name='Đến người')),
            ],
            options={
                'verbose_name': 'Quan hệ',
                'verbose_name_plural': 'Quan hệ',
                'unique_together': {('genealogy', 'from_person', 'to_person', 'relationship_type')},
            },
        ),
    ]
