# Generated by Django 6.0.1 on 2026-04-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_genealogy_genealogyperson_genealogyspouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='person_code',
            field=models.CharField(blank=True, help_text='VD: 04.05.001 (Chi.Đời.STT)', max_length=12, null=True, unique=True, verbose_name='Mã người'),
        ),
    ]
