# Generated by Django 6.0.1 on 2026-04-02 01:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_person_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_code', models.CharField(default=core.models.generate_draft_code, max_length=12, unique=True, verbose_name='Mã bản khai')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('submitter_name', models.CharField(max_length=100, verbose_name='Họ tên người khai')),
                ('submitter_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('submitter_relation', models.CharField(blank=True, help_text='VD: Con trai trưởng, Chi 4, Đời 6', max_length=200, verbose_name='Quan hệ với dòng họ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú chung')),
                ('status', models.CharField(choices=[('draft', 'Đang soạn'), ('submitted', 'Đã gửi'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('review_notes', models.TextField(blank=True, verbose_name='Ghi chú duyệt')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
            ],
            options={
                'verbose_name': 'Bản khai gia phả',
                'verbose_name_plural': 'Các bản khai gia phả',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.PositiveIntegerField(verbose_name='Số TT trong bản khai')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('birth_date', models.CharField(blank=True, max_length=50, verbose_name='Ngày sinh')),
                ('death_date', models.CharField(blank=True, max_length=50, verbose_name='Ngày mất')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drafts/', verbose_name='Ảnh')),
                ('relation_to_submitter', models.CharField(choices=[('self', 'Bản thân người khai'), ('father', 'Cha'), ('mother', 'Mẹ'), ('spouse', 'Vợ/Chồng'), ('child', 'Con'), ('sibling', 'Anh/Chị/Em'), ('grandparent', 'Ông/Bà'), ('grandchild', 'Cháu'), ('uncle_aunt', 'Chú/Bác/Cô/Dì'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Quan hệ với người khai')),
                ('father_temp_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cha (Số TT)')),
                ('mother_temp_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mẹ (Số TT)')),
                ('spouse_temp_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vợ/Chồng (Số TT)')),
                ('birth_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Con thứ')),
                ('chi_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chi số')),
                ('generation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Đời thứ')),
                ('action', models.CharField(choices=[('pending', 'Chờ xử lý'), ('create_new', 'Tạo mới'), ('link_existing', 'Liên kết người đã có'), ('skip', 'Bỏ qua')], default='pending', max_length=15, verbose_name='Hành động khi duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.familymember', verbose_name='Liên kết thành viên')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.draftsubmission', verbose_name='Bản khai')),
            ],
            options={
                'verbose_name': 'Người trong bản khai',
                'verbose_name_plural': 'Người trong bản khai',
                'ordering': ['submission', 'temp_id'],
                'unique_together': {('submission', 'temp_id')},
            },
        ),
    ]
