# Generated by Django 6.0.1 on 2026-04-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_draft_submission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouserelation',
            name='status',
            field=models.CharField(choices=[('married', 'Đang hôn phối'), ('divorced', 'Đã ly hôn'), ('widowed', 'Góa')], default='married', max_length=10, verbose_name='Tình trạng'),
        ),
    ]
