# Generated by Django 6.0.1 on 2026-04-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_spouse_relation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftperson',
            name='spouse_status',
            field=models.CharField(blank=True, choices=[('married', 'Đang hôn phối'), ('divorced', 'Đã ly hôn'), ('widowed', 'Góa')], default='married', max_length=10, verbose_name='Tình trạng hôn nhân'),
        ),
    ]
