# Generated by Django 6.0.1 on 2026-04-02 05:17

import django.db.models.deletion
from django.db import migrations, models


def migrate_spouse_data(apps, schema_editor):
    """Move spouse_temp_id/spouse_status data into DraftSpouseRelation"""
    DraftPerson = apps.get_model('core', 'DraftPerson')
    DraftSpouseRelation = apps.get_model('core', 'DraftSpouseRelation')

    # Find all persons with spouse_temp_id set, only process where temp_id < spouse_temp_id
    # to avoid creating duplicates (since both sides store the relation)
    for p in DraftPerson.objects.filter(spouse_temp_id__isnull=False):
        if p.temp_id < p.spouse_temp_id:
            DraftSpouseRelation.objects.get_or_create(
                submission=p.submission,
                person1_temp_id=p.temp_id,
                person2_temp_id=p.spouse_temp_id,
                defaults={'status': p.spouse_status or 'married'},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_draft_spouse_status'),
    ]

    operations = [
        # Step 1: Create the new table
        migrations.CreateModel(
            name='DraftSpouseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1_temp_id', models.PositiveIntegerField(verbose_name='Người 1 (Số TT)')),
                ('person2_temp_id', models.PositiveIntegerField(verbose_name='Người 2 (Số TT)')),
                ('status', models.CharField(choices=[('married', 'Đang hôn phối'), ('divorced', 'Đã ly hôn'), ('widowed', 'Góa')], default='married', max_length=10, verbose_name='Tình trạng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations', to='core.draftsubmission', verbose_name='Bản khai')),
            ],
            options={
                'verbose_name': 'Quan hệ vợ chồng (bản khai)',
                'verbose_name_plural': 'Các quan hệ vợ chồng (bản khai)',
                'unique_together': {('submission', 'person1_temp_id', 'person2_temp_id')},
            },
        ),
        # Step 2: Migrate existing data
        migrations.RunPython(migrate_spouse_data, migrations.RunPython.noop),
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name='draftperson',
            name='spouse_status',
        ),
        migrations.RemoveField(
            model_name='draftperson',
            name='spouse_temp_id',
        ),
    ]
