# Generated by Django 6.0.1 on 2026-04-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_spouse_relation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftspouserelation',
            name='wife_order',
            field=models.PositiveIntegerField(default=1, help_text='1=Bà Cả, 2=Bà Hai, 3=Bà Ba...', verbose_name='Thứ tự bà'),
        ),
    ]
