# Generated by Django 6.0.1 on 2026-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wife_order_to_draft_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsubmission',
            name='layout_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Bố cục phả đồ'),
        ),
    ]
