# Generated by Django 6.0.1 on 2026-04-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_layout_data_to_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftperson',
            name='is_dinh',
            field=models.BooleanField(default=False, help_text='Nam giới thuộc dòng trực hệ = Đinh', verbose_name='Tính Đinh'),
        ),
        migrations.AddField(
            model_name='draftperson',
            name='member_type',
            field=models.CharField(choices=[('blood', 'Dòng trực hệ'), ('spouse_in', 'Dâu/Rể'), ('child_out', 'Cháu ngoại'), ('adopted_in', 'Nhập tịch'), ('adopted_child', 'Con nuôi')], default='blood', help_text='Dòng trực hệ / Dâu-Rể / Con nuôi / Cháu ngoại / Nhập tịch', max_length=20, verbose_name='Loại thành viên'),
        ),
    ]
