# Generated by Django 6.0.1 on 2026-04-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_deceased_and_lunar_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftperson',
            name='death_date_lunar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ngày mất (âm lịch)'),
        ),
        migrations.AddField(
            model_name='draftperson',
            name='is_deceased',
            field=models.BooleanField(default=False, verbose_name='Đã mất'),
        ),
        migrations.AlterField(
            model_name='draftperson',
            name='death_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ngày mất (dương lịch)'),
        ),
    ]
